### ISSUE TITLE
how to debug the wasm container

### ISSUE THREAD

**Issue by defims** [containerd/runwasi#46]
ctr run work well:
```bash
sudo ctr run --rm --runtime=io.containerd.wasmedge.v1 docker.io/library/wasmtest:latest testwasm /wasm echo 'hello'
```

but kubectl apply yaml failed. I don't know how to debug the wasm container(from scratch). for example echo container logs.

containerd-template.toml added config:
```yaml
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.wasmtime]
      runtime_type = "io.containerd.wasmtime.v1"
```
k8s.yml:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wasmtest
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wasmtest
            port:
              number: 3000
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime
handler: wasmtime
---
kind: Service
apiVersion: v1
metadata:
  name: wasmtest
  labels:
    name: wasmtest
spec:
  ports:
  - name: wasmtest3000
    protocol: TCP
    port: 3000
  selector:
    app: wasmtest
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wasmtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasmtest
  template:
    metadata:
      labels:
        app: wasmtest
    spec:
      runtimeClassName: wasmtime
      containers:
      - name: wasmtest
        image: docker.io/library/wasmtest:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 3000
```
```yaml
microk8s kubectl apply -f k8s.yml
```
