### ISSUE TITLE
k3s kubectl logs return empty logs

### ISSUE THREAD

**Issue by defims** [containerd/runwasi#50]
ctr run directly got right stdout logs
```bash
sudo k3s ctr image import --all-platforms target/wasm32-wasi/debug/img.tar #img.tar is build from cd crates/wasi-demo-app && cargo build && cargo build --features oci-v1-tar && cd ../../
sudo k3s ctr run --rm --runtime=io.containerd.wasmtime.v1 ghcr.io/containerd/runwasi/wasi-demo-app:latest wasi-demo-app #need containerd-shim-wasmtime-v1 avaibled by running make && make install 
```
<img width="976" alt="image" src="https://user-images.githubusercontent.com/767580/211990006-b74d88c7-f88d-4bfa-93ae-0672bc5c5c64.png">

but when I run it with kubectl, I got empty pod logs
```bash
sudo k3s kubectl apply -f wasm.yml # need configure containerd with configure file like below
sudo k3s kubectl get pods
sudo k3s kubectl logs wasi-demo-xxx
```
<img width="966" alt="image" src="https://user-images.githubusercontent.com/767580/211988834-41f415a3-17d3-47a1-bd98-a5555fb9394a.png">

the wasm.yml is:
```yaml
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime
handler: wasmtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasi-demo
  labels:
    app: wasi-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasi-demo
  template:
    metadata:
      labels:
        app: wasi-demo
    spec:
      runtimeClassName: wasmtime
      containers:
      - name: demo
        image: ghcr.io/containerd/runwasi/wasi-demo-app:latest
        imagePullPolicy: Never
```
/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl is:
```yaml
version = 2

[plugins."io.containerd.internal.v1.opt"]
  path = "/var/lib/rancher/k3s/agent/containerd"
[plugins."io.containerd.grpc.v1.cri"]
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  enable_unprivileged_ports = true
  enable_unprivileged_icmp = true
  sandbox_image = "rancher/mirrored-pause:3.6"

[plugins."io.containerd.grpc.v1.cri".containerd]
  snapshotter = "overlayfs"
  disable_snapshot_annotations = true


[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/7c994f47fd344e1637da337b92c51433c255b387d207b30b3e0262779457afe4/bin"
  conf_dir = "/var/lib/rancher/k3s/agent/etc/cni/net.d"


[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.wasmedge]
  runtime_type = "io.containerd.wasmedge.v1"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.wasmtime]
  runtime_type = "io.containerd.wasmtime.v1"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  SystemdCgroup = true
```
containerd shims are in /usr/local/bin
<img width="577" alt="image" src="https://user-images.githubusercontent.com/767580/211996550-a963a2c2-e7d8-42ea-a13c-c294b0ed0be5.png">
