### ISSUE TITLE
Adding containerd config options for the shim

### ISSUE THREAD

**Issue by jsturtevant** [containerd/runwasi#573]
Consider adding containerd config options for the shim to enable feature code paths. I don't believe Rust compilation flags would be desirable in cases like this since the user is likely to not have compiled the shim in the first place. Adding containerd config options for the shim would allow for on node configuration and debugging. It could also provide a path for turning on and off newly release / unstable features w/o recompilation.

Originally from https://github.com/spinkube/containerd-shim-spin/issues/79#issuecomment-2069416415

**Comment by jprendes** [comment]
IIUC, a shim can define its own options as a protobuf message
https://github.com/containerd/containerd/blob/main/core/runtime/v2/README.md#container-level-shim-configuration

**Comment by kate-goldenring** [comment]
As @jprendes mentioned, it looks like the options set in the containerd config should be passed in the `CreateTaskRequest` message under the `options` field. This is received during `create` request (issued by `containerd`) in `runwasi`. To test out configuring options with `containerd`, I added an option to the `config.toml` for the Spin shim and restarted the `containerd` service:
```
 [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.spin]
    runtime_type = "io.containerd.spin.v2"

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.spin.options]
    Foo = "bar"
```

I then built the shim locally with a print statement [here](https://github.com/containerd/runwasi/blob/eab0db3c6eb919aa72900928eedc73d373e1b03d/crates/containerd-shim-wasm/src/sandbox/shim/local.rs#L107) in `runwasi`:
```
    fn task_create(&self, req: CreateTaskRequest) -> Result<CreateTaskResponse> {
        log::info!("task_create called with options: {:?}", req.options);
```

I expected the option to be passed by containerd and logged but there are still not options set:
```
May 17 16:39:35 kagold-ThinkPad-X1-Carbon-6th containerd[738]: time="2024-05-17T23:39:35.20109351Z" level=info msg="task_create;"
May 17 16:39:35 kagold-ThinkPad-X1-Carbon-6th containerd[738]: time="2024-05-17T23:39:35.201106634Z" level=info msg="task_create called with options: MessageField(None)"
```

Does anyone have any recommendations for how to approach this? `runc` passes the following options:
```toml
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            BinaryName = ""
            CriuImagePath = ""
            CriuPath = ""
            CriuWorkPath = ""
            IoGid = 0
            IoUid = 0
            NoNewKeyring = false
            NoPivotRoot = false
            Root = ""
            ShimCgroup = ""
            SystemdCgroup = true
```
